[package]
name = "lylib"
version = "0.32.2"
edition = "2024"

[dependencies]
anyhow = "1.0"
derivative = "2.2"
mimalloc = { version = "*", default-features = false }
rustc-hash = "2.1"
thiserror = "2.0.18"

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "interpret"
harness = false
